language: node_js

node_js:
  - 4
  - 5
  - 6

cache:
  directories:
    - node_modules

install:
  - wget https://github.com/jgm/pandoc/releases/download/1.17.2/pandoc-1.17.2-1-amd64.deb
  - sudo dpkg -i pandoc-1.17.2-1-amd64.deb

script:
  - make lint
  - make cover

after_success:
  - |
    if [[ $TRAVIS_NODE_VERSION == 6* ]]; then
      bash <(curl -s https://codecov.io/bash);
    fi

notifications:
  webhooks:
    urls:
      - secure: "c7sJb5i92rK48bkT/JEqjyrznBfLUAHcPr7vXTuFZGX5jn/g0tssCtsDiN08mvULuIJF2F2av/8SF9R2cSpeKkC69I9+YUn+uItq4zFISxzh7q3QfcWvQnbizCkjVDU+AxsTf4m9Kq3eatxwPNuAxRc6PGeaYQ5/NeMYFDkYGCk=" # Gitter
